version: '3.9'

services:
  job-portal:
    image: butaji9l/job-portal:latest
    container_name: job-portal
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - BASE_URI=http://localhost:4200
      - ACCESS_TOKEN_DURATION=1H
      - REFRESH_TOKEN_DURATION=1D
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jobportal
      - SPRING_DATASOURCE_USERNAME=jobportal # not good practice, it is better to store in 'secrets'
      - SPRING_DATASOURCE_PASSWORD=jobportal # not good practice, it is better to store in 'secrets'
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - EMAIL_STMP_HOST=smtp.gmail.com # specify another stmp in case you do not use gmail
      - EMAIL_PORT=587
      - EMAIL_NOTIFICATION_APP_USERNAME=muni.job.portal.application@gmail.com # add your email (according to stmp) (not good practice, it is better to store in 'secrets')
      - EMAIL_NOTIFICATION_APP_PASSWORD=cfvbocfzpaoektzs # generate password for application in gmail (not good practice, it is better to store in 'secrets')
      - NOTIFICATIONS_ENABLED=true # enable notifications
      - LIQUIBASE_CONTEXTS=default, data, demo
    volumes:
      - app-data:/tmp

  frontend:
    image: job-portal-fe
    container_name: job-portal-fe
    build:
      context: ./job-portal-fe
    ports:
      - "4200:4200"
    depends_on:
      - job-portal
#
#  frontend-admin:
#    image: job-portal-fe-admin
#    container_name: job-portal-fe-admin
#    build:
#      context: ./job-portal-fe-admin
#    ports:
#      - "4200:4200"
#    depends_on:
#      - job-portal

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jobportal # not good practice, it is better to store in 'secrets'
      - POSTGRES_PASSWORD=jobportal # not good practice, it is better to store in 'secrets'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  app-data:

